### ISSUE TITLE
How long to latent consistency model take to generate an image compared to diffusion models?

### ISSUE THREAD

**Issue by ninjasaid2k** [luosiallen/latent-consistency-model#1]
A thing about step numbers, is that it does not provide that much information in inference times. It is possible that it might take fewer steps counts to obtain a sharp image but the trade-off might be that each step takes longer, can you tell me if the steps don't take significantly longer in comparison to diffusion models or if there's any other trade-offs?

**Comment by luosiallen** [comment]
Thanks for mentioning it. Our LCM **only requires one network forward** per sampling step, compared with DPM-Solver, DPM-Solver++ that requires 2 network forward per sampling step (order=2). In addition, when using the Classifier-Free Guidance in LCM, LCM **still only requires network forward**, since we have already distilled the CFG into our model, compared with DPM-Solver, DPM-Solver++ that requires larger GPU memory when computing the unconditional score and conditional score at the same time. **LCM is **super fast** without sacrifising image quality**. We compare the inference time at the setting of 768 x 768 resolution, w=8, batchsize=4, inference steps=4 using a A800 GPU.

The results of **average inference time per step** is: 

(DPM-Solver++): 1.1039 second
(LCM) :                 **0.5652** second

We are working currently to release our generation process demos. Thanks for asking again!
