### ISSUE TITLE
Question regarding BoundaryConditionScalings

### ISSUE THREAD

**Issue by saddam213** [luosiallen/latent-consistency-model#30]
Hey Team,

I have successfully ported LCM to native C#, I am just adding some UI settings and have a few questions regarding a few fields

https://github.com/saddam213/OnnxStack/blob/master/OnnxStack.StableDiffusion/Diffusers/LatentConsistency/TextDiffuser.cs
https://github.com/saddam213/OnnxStack/blob/master/OnnxStack.StableDiffusion/Schedulers/LatentConsistency/LCMScheduler.cs

1. BoundaryConditionScalings, there is a fixed variable `sigma_data = 0.5  # Default: 0.5` is this something that should be adjusted by the end user, if so what is the recommended min/max
2. Original Inference Steps, like wise is this something we should add next to the Inference Steps slider? or is it safe to fix it to a range of 30-50

Loving LCM, images are great even with a low step count, awesome work

**Comment by luosiallen** [comment]
Hi @saddam213, thanks for enjoying the LCM. 
1. The sigma_data=0.5 should be fixed. Since the LCM model is training with this fixed constant. The inference should be the same with the training process.
2.  The `lcm_original_steps` should also be fixed during inference, for LCM_Dreamshaper_v7, this should also be fixed with `lcm_original_steps=50` . The `lcm_origin_steps` depends on how many skipping steps we use during training. So we should also use the same `lcm_origin_steps` as during the LCM training at the time of inference. This is not an option to be chosen at the time of inference, but rather at the time of training.

**Comment by saddam213** [comment]
Awesome that makes sense, I did not see any difference when I played with fixed value anyway.

Also managed to get ImageToImage working, all in native c#, no python needed :)

**Comment by luosiallen** [comment]
Thanks! We will add official Image2Image pipeline as soon as possible.

**Comment by saddam213** [comment]
8 steps, 1.5 seconds, your model is awesome
![280117581-7208ff3e-d5c5-4ec9-970a-601d1584df1a](https://github.com/luosiallen/latent-consistency-model/assets/4353684/47fb4f45-e25a-4605-96ac-a8d7701fa2fa)

**Comment by luosiallen** [comment]
Really Cool! More good to come, trying to truly bring it down to <= 4 steps (don't need 8 steps anymore) and SD-XL.

**Comment by luosiallen** [comment]
This is for Windows users right? @saddam213

**Comment by saddam213** [comment]
Yes, this is fully written in .NET, no need for diffusers, python or any api 

The UI is windows only, but the codebase is .NET 7 so can be compiled for Linux and Mac as well
