### ISSUE TITLE
About guidance_scale

### ISSUE THREAD

**Issue by haofanwang** [luosiallen/latent-consistency-model#40]
Hi @luosiallen, I love your work! But I have one question.

As suggested in [latent-consistency/lcm-lora-sdv1-5](https://huggingface.co/latent-consistency/lcm-lora-sdv1-5), it is recommended to disable guidance_scale or use values between 1.0 and 2.0. The effect of guidance_scale can be found in [this post](https://twitter.com/Haofan_Wang/status/1723219204537827449). But in the paper, it seems that it should be fine to set the guidance_scale to 7.5 for classifier-free guidance. What causes this difference?

**Comment by luosiallen** [comment]
The detailed implementation of LCM LoRA is slightly different with the origin LCM training. We do not add additional flexible w_embedding into LCM. We distill a fix cfg scale with 7.5 during LCM training already.

**Comment by zjysteven** [comment]
@luosiallen I have a follow-up question on CFG guidance used during training. In the released training code for LCM lora, a random CFG guidance within [`w_min`, `w_max`] will be sampled at each iteration, and `w_min` = 5.0, `w_max` = 15.0 as shown below.
https://github.com/luosiallen/latent-consistency-model/blob/a9ad79587cc8bd1e404ccd1a3056a3da969b2f62/LCM_Training_Script/consistency_distillation/train_lcm_distill_lora_sd_wds.py#L644-L665

However, in the report it is stated that a fixed CFG scale = 7.5 is used. 
![image](https://github.com/luosiallen/latent-consistency-model/assets/19763611/4551bae5-37d4-45ed-8429-53d0589918fd)
I was wondering why there's a difference between the report and the code and if this is something we should take into account when training our own LCM lora. Thanks in advance.

**Comment by jojkaart** [comment]
Before the LCM Lora was released, luosiallen released a distilled version of dreamshaper7 as a full model. I'd assume the CFG variation in the training code is a remnant from training that model and LCM Lora was trained strictly with CFG 7.5.
The distilled model accepted the CFG as a direct model parameter rather than being a part of the sampling process. I assume the CFG parameter was omitted to avoid changing the model architecture through the Lora.
